# Generated by Django 4.2.4 on 2023-08-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='country',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='pestle',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='source',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='topic',
        ),
    ]
