# Generated by Django 4.2.4 on 2023-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_datapoint_country_datapoint_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='added',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='published',
        ),
    ]
