# Generated by Django 4.2.4 on 2023-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_datapoint_added_remove_datapoint_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='added',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='published',
            field=models.TextField(blank=True, null=True),
        ),
    ]
