# Generated by Django 4.2.4 on 2023-08-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_datapoint_added_datapoint_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='likelihood',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='relevance',
        ),
    ]
