# Generated by Django 4.2.4 on 2023-08-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_datapoint_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='intensity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='likelihood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='relevance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
