# Generated by Django 4.2.4 on 2023-08-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_datapoint_intensity_datapoint_likelihood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='url',
        ),
    ]
