# Generated by Django 4.2.4 on 2023-08-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_datapoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
